// Generated by: npm run cf:typegen
// Bindings are defined in wrangler.toml

interface R2Bucket {
  put(
    key: string,
    value: ArrayBuffer | ArrayBufferView | string | ReadableStream | Blob | null,
    options?: R2PutOptions
  ): Promise<R2Object>;
  get(key: string): Promise<R2ObjectBody | null>;
  delete(key: string | string[]): Promise<void>;
}

interface R2PutOptions {
  httpMetadata?: { contentType?: string };
}

interface R2Object {
  key: string;
}

interface R2ObjectBody extends R2Object {
  body: ReadableStream;
}

interface Hyperdrive {
  connectionString: string;
}

interface CloudflareEnv {
  MENTOR_CONTENT: R2Bucket;
  HYPERDRIVE?: Hyperdrive;
  ASSETS: Fetcher;
  WORKER_SELF_REFERENCE: Fetcher;
}

interface Fetcher {
  fetch(input: RequestInfo, init?: RequestInit): Promise<Response>;
}
