/** Veritrex brand and contact details — single source of truth for UI copy. */

export const BRAND = {
  name: "Veritrex",
  domain: "veritrex.org",
  tagline: "Connect. Mentor. Elevate.",
  motto: "Mentorship that builds careers.",
  description:
    "Veritrex is a pioneer in professional infrastructure, building the world's most trusted ecosystem for mentorship and career advancement. We bridge ambitious professionals and institutional-grade validation.",
  aboutShort:
    "At the heart of Veritrex is our structured Mentor-Mentee Marketplace — accountable, accessible mentorship without high cost or network prerequisites.",
  email: "info@veritrex.com",
  phone: "9740001208",
  phoneDisplay: "+91 97400 01208",
  phoneHref: "tel:+919740001208",
  address: "172, Pentagon Passiflora, Sarjapura, Bengaluru 562125",
  city: "Bengaluru",
  website: "https://veritrex.org",
  freeMentorshipHoursCap: 5,
} as const;

export const BRAND_ABOUT = {
  intro:
    "Veritrex is a pioneer in professional infrastructure, building the world's most trusted ecosystem for mentorship and career advancement. We bridge the gap between ambitious professionals and institutional-grade validation, reshaping how industry leaders engage with emerging talent.",
  marketplace:
    "At the heart of Veritrex is our structured Mentor-Mentee Marketplace. Designed to remove high cost and network prerequisites, we provide structured, accountable, and accessible mentorship for early-career talent. Our ecosystem addresses a critical professional challenge: providing a trusted space for senior executives to forge a human legacy while offering an exclusive network for lateral companion matching and high-level peer interaction.",
  credibility:
    "What truly sets Veritrex apart is our commitment to absolute credibility. Powered by an immutable, multi-layered TrustScore Engine, our platform features blind submission rules to eliminate bias, anti-collusion safeguards, and rater-credibility weighting. This creates a completely fraud-resistant talent network.",
  referralHiring:
    "Beyond matching, we drive a landmark Referral Hiring framework built around milestone-split retention incentives (30/40/30) over a 180-day cycle — a model that aligns long-term performance with direct reward.",
  credibilityEngine:
    "Complemented by a dynamic Professional Credibility Engine that integrates rich portfolio evidence straight into the hiring workflow, we allow recruiters to vet talent seamlessly. Backed by structured credit mechanics, academic alliances, and an overarching mission of impact, Veritrex transforms unverified portfolios into definitive professional proof.",
  closing:
    "We are not just a marketplace; we are the structural foundation for verified connection, legacy building, and accelerated growth.",
} as const;

export const BRAND_META = {
  title: `${BRAND.name} — ${BRAND.tagline}`,
  description: BRAND.description,
} as const;

/** Static brand art generated by scripts/generate-brand-assets.mjs */
export const BRAND_ASSETS = {
  mark: {
    512: "/brand/mark-512.png",
    192: "/brand/mark-192.png",
    96: "/brand/mark-96.png",
    32: "/brand/mark-32.png",
  },
  lockup: {
    1200: "/brand/lockup-1200.png",
    800: "/brand/lockup-800.png",
    480: "/brand/lockup-480.png",
  },
  wordmark: {
    720: "/brand/wordmark-720.png",
    480: "/brand/wordmark-480.png",
    320: "/brand/wordmark-320.png",
    240: "/brand/wordmark-240.png",
  },
} as const;

export const BRAND_COLORS = {
  black: "#000000",
  navy: "#0A1628",
  teal: "#14B8A6",
  gold: "#FBBF24",
} as const;

/** Native aspect ratio of the full horizontal lockup source. */
export const LOCKUP_ASPECT = 1536 / 1024;

/** Native pixel aspect ratio of wordmark-480.png (icon + "VERITREX"). */
export const WORDMARK_ASPECT = 480 / 320;
